In [ ]:
import tensorflow
from tensorflow.keras.layers import Dense, Flatten, MaxPooling1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Dropout
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.losses import BinaryCrossentropy
# from tensorflow.keras.utils import to_categorical
# from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.metrics import binary_accuracy, AUC

In [ ]:
#batch_size=64
batch_size=1

In [ ]:
import numpy as np
a = np.random.rand(16384,1)
print(a)

[[0.42909526]
 [0.23721638]
 [0.10911285]
 ...
 [0.75503336]
 [0.99728585]
 [0.66225015]]


In [ ]:
from sklearn.model_selection import train_test_split
X, y = a, np.array([1])
X

array([[0.42909526],
       [0.23721638],
       [0.10911285],
       ...,
       [0.75503336],
       [0.99728585],
       [0.66225015]])

In [ ]:
y

array([1])

In [ ]:

X = np.transpose(X)
X

array([[0.42909526],
       [0.23721638],
       [0.10911285],
       ...,
       [0.75503336],
       [0.99728585],
       [0.66225015]])

In [ ]:
input_shape=(16384,1)

In [ ]:
model=Sequential()

model.add(Conv1D(filters=32, kernel_size=16, activation='relu', input_shape=input_shape))
model.add(MaxPooling1D(pool_size=4))

model.add(Conv1D(64, kernel_size=8, activation='relu'))
model.add(MaxPooling1D(pool_size=4))

model.add(Conv1D(128, kernel_size=8, activation='relu'))
#model.add(Conv1D(16, kernel_size=16, activation='relu'))
model.add(MaxPooling1D(pool_size=4))

model.add(Conv1D(256, kernel_size=8, activation='relu'))
#model.add(Conv1D(32, kernel_size=16, activation='relu'))
model.add(MaxPooling1D(pool_size=4))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1, activation='softmax'))

model.compile(optimizer= Adam(learning_rate=0.002, beta_1=0.9, beta_2=0.999, epsilon=1e-08),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_9 (Conv1D)           (None, 16369, 32)         544       
                                                                 
 max_pooling1d_8 (MaxPooling  (None, 4092, 32)         0         
 1D)                                                             
                                                                 
 conv1d_10 (Conv1D)          (None, 4085, 64)          16448     
                                                                 
 max_pooling1d_9 (MaxPooling  (None, 1021, 64)         0         
 1D)                                                             
                                                                 
 conv1d_11 (Conv1D)          (None, 1014, 128)         65664     
                                                                 
 max_pooling1d_10 (MaxPoolin  (None, 253, 128)        

In [ ]:
model.fit(X,y, epochs = 10)

ValueError: ignored